package com.mmt.ltxm.mapper;

import com.mmt.ltxm.model.Nav;
import com.mmt.ltxm.model.NavExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NavMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    long countByExample(NavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int deleteByExample(NavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int insert(Nav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int insertSelective(Nav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    List<Nav> selectByExample(NavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    Nav selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") Nav record, @Param("example") NavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int updateByExample(@Param("record") Nav record, @Param("example") NavExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int updateByPrimaryKeySelective(Nav record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV
     *
     * @mbg.generated Wed Nov 20 22:05:56 CST 2019
     */
    int updateByPrimaryKey(Nav record);
}